package init

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// CredentialStorageType represents where to store the credential.
type CredentialStorageType int

const (
	// StorageKeychain stores in macOS Keychain (keychain:service/account).
	StorageKeychain CredentialStorageType = iota
	// StorageFile stores in ~/.config/chaperone/secrets/<service-name>.
	StorageFile
	// StorageEnvFile appends to .env file (env:SERVICE_NAME_API_KEY).
	StorageEnvFile
)

// WriteCredential writes a credential to the chosen storage and returns the credential_ref.
// Returns:
//   - credential_ref string (e.g., "keychain:chaperone/openai")
//   - error if write fails
func WriteCredential(storageType CredentialStorageType, serviceName, credentialValue string) (string, error) {
	switch storageType {
	case StorageKeychain:
		return writeToKeychain(serviceName, credentialValue)
	case StorageFile:
		return writeToFile(serviceName, credentialValue)
	case StorageEnvFile:
		return writeToEnvFile(serviceName, credentialValue)
	default:
		return "", fmt.Errorf("unknown storage type: %d", storageType)
	}
}

// writeToKeychain writes the credential to macOS Keychain.
// Uses the pattern: keychain:chaperone/<service-name>
func writeToKeychain(serviceName, credentialValue string) (string, error) {
	// Platform check - only works on macOS
	if runtime.GOOS != "darwin" {
		return "", fmt.Errorf("keychain storage only works on macOS (current platform: %s)", runtime.GOOS)
	}

	keychainService := "chaperone"
	keychainAccount := serviceName

	// Delete existing entry if present (security will fail if item exists)
	deleteCmd := exec.Command("security", "delete-generic-password", "-s", keychainService, "-a", keychainAccount)
	_ = deleteCmd.Run() // Ignore error - item may not exist

	// Add new keychain item
	// security add-generic-password -s <service> -a <account> -w <password>
	addCmd := exec.Command("security", "add-generic-password",
		"-s", keychainService,
		"-a", keychainAccount,
		"-w", credentialValue,
	)

	output, err := addCmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("failed to write to keychain: %w (output: %s)", err, strings.TrimSpace(string(output)))
	}

	credentialRef := fmt.Sprintf("keychain:%s/%s", keychainService, keychainAccount)
	return credentialRef, nil
}

// writeToFile writes the credential to ~/.config/chaperone/secrets/<service-name>.
func writeToFile(serviceName, credentialValue string) (string, error) {
	// Get home directory
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get home directory: %w", err)
	}

	// Create secrets directory
	secretsDir := filepath.Join(homeDir, ".config", "chaperone", "secrets")
	if err := os.MkdirAll(secretsDir, 0700); err != nil {
		return "", fmt.Errorf("failed to create secrets directory: %w", err)
	}

	// Write credential to file
	secretFile := filepath.Join(secretsDir, serviceName)
	if err := os.WriteFile(secretFile, []byte(credentialValue), 0600); err != nil {
		return "", fmt.Errorf("failed to write credential file: %w", err)
	}

	credentialRef := fmt.Sprintf("file:%s", secretFile)
	return credentialRef, nil
}

// writeToEnvFile appends the credential to .env file in the current directory.
// Format: SERVICE_NAME_API_KEY=value
func writeToEnvFile(serviceName, credentialValue string) (string, error) {
	// Generate environment variable name
	// Convert service name to UPPER_SNAKE_CASE
	envVarName := toEnvVarName(serviceName)

	// Check if .env exists
	envFile := ".env"
	_, err := os.Stat(envFile)
	fileExists := err == nil

	// Open or create .env file (append mode)
	f, err := os.OpenFile(envFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		return "", fmt.Errorf("failed to open .env file: %w", err)
	}
	defer f.Close()

	// Add separator if file already exists and has content
	if fileExists {
		// Check if file ends with newline
		stat, _ := f.Stat()
		if stat.Size() > 0 {
			// Add newline before new entry
			if _, err := f.WriteString("\n"); err != nil {
				return "", fmt.Errorf("failed to write to .env file: %w", err)
			}
		}
	}

	// Write entry with comment
	entry := fmt.Sprintf("# %s API key (generated by chaperone init)\n%s=%s\n", serviceName, envVarName, credentialValue)
	if _, err := f.WriteString(entry); err != nil {
		return "", fmt.Errorf("failed to write to .env file: %w", err)
	}

	credentialRef := fmt.Sprintf("env:%s", envVarName)
	return credentialRef, nil
}

// toEnvVarName converts a service name to an environment variable name.
// Examples:
//   - "openai" → "OPENAI_API_KEY"
//   - "my-service" → "MY_SERVICE_API_KEY"
//   - "foo_bar" → "FOO_BAR_API_KEY"
func toEnvVarName(serviceName string) string {
	// Replace hyphens with underscores
	name := strings.ReplaceAll(serviceName, "-", "_")
	// Convert to uppercase
	name = strings.ToUpper(name)
	// Add _API_KEY suffix
	return name + "_API_KEY"
}
