package init

import (
	"fmt"
	"strings"

	"github.com/bmf/chaperone/internal/service"
)

// GenerateTOMLConfig creates a TOML configuration string from a GeneratedService.
// The output matches the config.Config structure and includes helpful comments.
func GenerateTOMLConfig(svc *GeneratedService) string {
	var sb strings.Builder

	// Service section header
	fmt.Fprintf(&sb, "# Service configuration for %s\n", svc.Name)
	fmt.Fprintf(&sb, "# Generated by chaperone init wizard\n\n")

	// Service entry
	fmt.Fprintf(&sb, "[[services]]\n")
	fmt.Fprintf(&sb, "name = %q\n", svc.Name)
	fmt.Fprintf(&sb, "host_pattern = %q\n", svc.HostPattern)
	fmt.Fprintf(&sb, "auth_strategy = %q\n", svc.AuthStrategy)

	// If using header strategy, include header name
	if strings.HasPrefix(svc.AuthStrategy, "header:") {
		headerName := strings.TrimPrefix(svc.AuthStrategy, "header:")
		fmt.Fprintf(&sb, "header_name = %q\n", headerName)
	}

	fmt.Fprintf(&sb, "credential_ref = %q\n\n", svc.CredentialRef)

	// Policy section (if present)
	if svc.Policy != nil && (len(svc.Policy.AllowedMethods) > 0 || len(svc.Policy.AllowedPaths) > 0 || svc.Policy.MaxBodyBytes > 0) {
		fmt.Fprintf(&sb, "[services.policy]\n")

		if len(svc.Policy.AllowedMethods) > 0 {
			fmt.Fprintf(&sb, "allowed_methods = [")
			for i, method := range svc.Policy.AllowedMethods {
				if i > 0 {
					fmt.Fprintf(&sb, ", ")
				}
				fmt.Fprintf(&sb, "%q", method)
			}
			fmt.Fprintf(&sb, "]\n")
		}

		if len(svc.Policy.AllowedPaths) > 0 {
			fmt.Fprintf(&sb, "allowed_paths = [")
			for i, path := range svc.Policy.AllowedPaths {
				if i > 0 {
					fmt.Fprintf(&sb, ", ")
				}
				fmt.Fprintf(&sb, "%q", path)
			}
			fmt.Fprintf(&sb, "]\n")
		}

		if svc.Policy.MaxBodyBytes > 0 {
			fmt.Fprintf(&sb, "max_body_bytes = %d  # %s\n", svc.Policy.MaxBodyBytes, FormatBodySize(svc.Policy.MaxBodyBytes))
		}

		fmt.Fprintf(&sb, "\n")
	}

	return sb.String()
}

// InferAuthStrategy determines the auth strategy based on the detected auth header.
// Returns:
//   - "bearer" if header is "Authorization" (case-insensitive)
//   - "header:X-Header-Name" for any other header
func InferAuthStrategy(headerName string) string {
	if strings.ToLower(headerName) == "authorization" {
		return "bearer"
	}
	return fmt.Sprintf("header:%s", headerName)
}

// BuildGeneratedService creates a GeneratedService from detection findings and user inputs.
func BuildGeneratedService(
	serviceName string,
	findings *ServiceFindings,
	topFinding *Finding,
	credentialRef string,
) *GeneratedService {
	if findings == nil || topFinding == nil {
		return nil
	}

	// Infer auth strategy from header name
	authStrategy := InferAuthStrategy(topFinding.HeaderName)

	// Build policy from findings
	policy := buildPolicy(findings.Policy)

	return &GeneratedService{
		Name:          serviceName,
		HostPattern:   findings.Host,
		AuthStrategy:  authStrategy,
		CredentialRef: credentialRef,
		Policy:        policy,
	}
}

// buildPolicy converts PolicyFindings to service.Policy.
func buildPolicy(pf *PolicyFindings) *service.Policy {
	if pf == nil {
		return nil
	}

	policy := &service.Policy{}

	// Convert methods map to slice
	if len(pf.Methods) > 0 {
		methods := make([]string, 0, len(pf.Methods))
		for method := range pf.Methods {
			methods = append(methods, method)
		}
		policy.AllowedMethods = methods
	}

	// Convert paths map to slice and generalize
	if len(pf.Paths) > 0 {
		paths := make([]string, 0, len(pf.Paths))
		for path := range pf.Paths {
			paths = append(paths, path)
		}
		policy.AllowedPaths = GeneralizePathPatterns(paths)
	}

	// Infer max body bytes with headroom
	if pf.MaxBodyBytes > 0 {
		policy.MaxBodyBytes = InferMaxBodyBytes(pf.MaxBodyBytes)
	}

	return policy
}
