package cmd

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/bmf/chaperone/internal/config"
	chaperoneInit "github.com/bmf/chaperone/internal/init"
	"github.com/bmf/chaperone/internal/log"
	"github.com/bmf/chaperone/internal/mitm"
	"github.com/bmf/chaperone/internal/proxy"
	"github.com/bmf/chaperone/internal/shutdown"
	"github.com/spf13/cobra"
)

var (
	initSentinel       string
	initNonInteractive bool
	initDryRun         bool
)

// supportedServices provides pre-built templates for common services.
// These are used by the legacy template-based init command.
var supportedServices = map[string]string{
	"openai": `# OpenAI service configuration
# Generated by chaperone init

[server]
address = "127.0.0.1"
port = 4010

[logging]
level = "info"

[services.openai]
host_pattern = "api.openai.com"
auth_strategy = "bearer"
credential_ref = "env:OPENAI_API_KEY"

[services.openai.policy]
allowed_methods = ["GET", "POST"]
allowed_paths = ["/v1/*"]
max_body_bytes = 10485760  # 10MB
`,
	"anthropic": `# Anthropic service configuration
# Generated by chaperone init

[server]
address = "127.0.0.1"
port = 4010

[logging]
level = "info"

[services.anthropic]
host_pattern = "api.anthropic.com"
auth_strategy = "header:x-api-key"
credential_ref = "env:ANTHROPIC_API_KEY"

[services.anthropic.policy]
allowed_methods = ["GET", "POST"]
allowed_paths = ["/v1/*"]
max_body_bytes = 10485760  # 10MB
`,
}

var initCmd = &cobra.Command{
	Use:   "init [service]",
	Short: "Initialize configuration with wizard or template",
	Long: `Initialize chaperone configuration interactively or from a template.

Without arguments, runs an interactive wizard that:
1. Starts a detection proxy to discover how apps pass credentials
2. Lets you configure detected services one at a time
3. Saves credentials to keychain, file, or .env
4. Generates a chaperone.toml configuration

With a service name argument (openai, anthropic), generates a template config.

Examples:
  chaperone init                        # Interactive wizard
  chaperone init --sentinel "test123"   # Wizard with sentinel value
  chaperone init --dry-run              # Preview config without saving
  chaperone init openai                 # Generate OpenAI template
  chaperone init anthropic              # Generate Anthropic template`,
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)

	initCmd.Flags().StringVar(&initSentinel, "sentinel", "", "Sentinel value to search for in requests (100% confidence match)")
	initCmd.Flags().BoolVarP(&initNonInteractive, "yes", "y", false, "Non-interactive mode, accept defaults")
	initCmd.Flags().BoolVar(&initDryRun, "dry-run", false, "Show generated config without saving")
}

func runInit(cmd *cobra.Command, args []string) error {
	// If a service name is provided, use template-based init
	if len(args) == 1 {
		return runTemplateInit(args[0])
	}

	// Otherwise, run the interactive wizard
	return runWizardInit()
}

// runTemplateInit generates a config from a pre-built template
func runTemplateInit(service string) error {
	template, ok := supportedServices[service]
	if !ok {
		supported := make([]string, 0, len(supportedServices))
		for name := range supportedServices {
			supported = append(supported, name)
		}
		return fmt.Errorf("unsupported service %q, supported: %v", service, supported)
	}

	// Write to chaperone.toml in current directory
	if err := os.WriteFile("chaperone.toml", []byte(template), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Printf("Created chaperone.toml for %s\n", service)
	fmt.Println("\nNext steps:")
	fmt.Println("1. Trust the CA certificate: chaperone ca-cert")
	fmt.Println("2. Start the proxy: chaperone inject")
	return nil
}

// runWizardInit runs the interactive init wizard
func runWizardInit() error {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Create wizard with configuration
	wizardCfg := chaperoneInit.DefaultWizardConfig()
	wizardCfg.SentinelValue = initSentinel
	wizardCfg.NonInteractive = initNonInteractive
	wizardCfg.DryRun = initDryRun

	wizard := chaperoneInit.NewWizard(wizardCfg)

	// Print introduction
	wizard.PrintIntroduction()

	// Step 1: Configure proxy settings
	wizardCfg, err := wizard.Step1ConfigureProxy()
	if err != nil {
		return fmt.Errorf("failed to configure proxy: %w", err)
	}

	// Initialize detection
	wizard.InitializeDetection()

	// Setup CA
	caDir, caKeyPath, caCertPath, err := getCAPath()
	if err != nil {
		return fmt.Errorf("failed to get CA path: %w", err)
	}

	if err := os.MkdirAll(caDir, 0700); err != nil {
		return fmt.Errorf("failed to create CA directory: %w", err)
	}

	_, keyErr := os.Stat(caKeyPath)
	_, certErr := os.Stat(caCertPath)
	isNewCA := keyErr != nil || certErr != nil

	ca, err := mitm.LoadOrGenerateCA(caKeyPath, caCertPath)
	if err != nil {
		return fmt.Errorf("failed to initialize CA: %w", err)
	}

	// Create minimal config for proxy
	cfg := &config.Config{
		Server: config.ServerConfig{
			Address: wizardCfg.Address,
			Port:    wizardCfg.Port,
		},
		Logging: config.LoggingConfig{
			Level: "info",
		},
	}
	cfg.SetDefaults()

	// Setup logging
	setupLogging(cfg)

	if isNewCA {
		log.Info(ctx, "generated new CA certificate",
			"cert_path", caCertPath,
			"key_path", caKeyPath,
		)
	}

	certCache := mitm.NewCertCache(ca, slog.Default())
	shutdownMgr := shutdown.NewManager(slog.Default())

	// Step 2: Start detection proxy
	wizard.PrintDetectionInstructions(cfg)

	// Create init proxy with detector
	server := proxy.NewInitProxy(cfg, slog.Default(), shutdownMgr, certCache, wizard.GetDetector(), wizard.GetEvidence(), func(host string, finding *chaperoneInit.Finding) {
		wizard.ReportFinding(host, finding)
	})

	if err := server.Start(); err != nil {
		return fmt.Errorf("failed to start init proxy: %w", err)
	}

	// Wait for Ctrl+C
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)
	<-sigChan
	signal.Stop(sigChan)

	fmt.Println("\n\nStopping detection proxy...")

	// Stop proxy
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer shutdownCancel()
	if err := shutdownMgr.Shutdown(5 * time.Second); err != nil {
		// Ignore timeout errors during shutdown
		if shutdownCtx.Err() == nil {
			fmt.Printf("Warning: shutdown error: %v\n", err)
		}
	}

	// Step 3: Review findings
	host, err := wizard.Step3ReviewFindings()
	if err != nil {
		return fmt.Errorf("failed to review findings: %w", err)
	}
	if host == "" {
		return nil // User quit
	}

	// Step 4: Configure the selected service
	svc, err := wizard.Step4ConfigureService(ctx, host)
	if err != nil {
		return fmt.Errorf("failed to configure service: %w", err)
	}
	if svc == nil {
		return nil // User quit
	}

	// Step 5: Save configuration
	if err := wizard.Step5SaveConfig(svc); err != nil {
		return fmt.Errorf("failed to save config: %w", err)
	}

	return nil
}
